FROM wordpress:php8.3-fpm
MAINTAINER Open State Foundation <developers@openstate.eu>

RUN echo "Europe/Amsterdam" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales msmtp msmtp-mta zip wget

RUN sed -i -e 's/# nl_NL.UTF-8 UTF-8/nl_NL.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales

# Install composer
RUN cd /usr/local/bin && wget https://raw.githubusercontent.com/composer/getcomposer.org/5eb0614d3fa7130b363698d3dca52c619b463615/web/installer -O - -q | php -- --quiet && mv composer.phar composer

# Install WP-CLI
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# Needed for CiviCRM
RUN pecl install psr-1.2.0 && docker-php-ext-enable psr

ADD msmtprc /etc/msmtprc

# Configure php-fpm to use sendmail and raise limits
RUN printf '\nphp_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i\n' >> /usr/local/etc/php-fpm.conf
RUN sed -i 's/pm.max_children = 5/pm.max_children = 20/' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.start_servers = 2/pm.start_servers = 3/' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.min_spare_servers = 1/pm.min_spare_servers = 2/' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.max_spare_servers = 3/pm.max_spare_servers = 5/' /usr/local/etc/php-fpm.d/www.conf

RUN echo 'upload_max_filesize = 200M' >> /usr/local/etc/php/php.ini
RUN echo 'post_max_size = 200M' >> /usr/local/etc/php/php.ini

# Debug
#RUN sed -i '/error_log = \/proc\/self\/fd\/2/a log_level = debug' /usr/local/etc/php-fpm.conf
#RUN sed -i '/access.log = \/proc\/self\/fd\/2/a php_admin_value[error_log] = /proc/self/fd/2' /usr/local/etc/php-fpm.conf
#RUN sed -i '/access.log = \/proc\/self\/fd\/2/a php_flag[display_errors] = on' /usr/local/etc/php-fpm.conf
#RUN sed -i '/access.log = \/proc\/self\/fd\/2/a php_admin_flag[log_errors] = on' /usr/local/etc/php-fpm.conf
