version: '3.1'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../log/nginx/:/var/log/nginx/
      - app_volume:/var/www/html
      - ../wp-content/:/var/www/html/wp-content/
      - socket_volume:/socket
    restart: always
    networks:
      - nginx-load-balancer
      - network
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    secrets:
      - db_name
      - db_user
      - db_password
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME_FILE: /run/secrets/db_name
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('SUNRISE', 'on');
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', true);
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
        define('WPMS_ON', true);
        define('WPMS_MAIL_FROM', 'developers@openstate.eu');
        define('WPMS_MAIL_FROM_NAME', 'Open State Foundation developers');
        define('WPMS_MAILER', 'mail');
    volumes:
      - app_volume:/var/www/html
      - ../wp-content/:/var/www/html/wp-content/
      - socket_volume:/socket
    restart: always
    networks:
      - network
  mysql:
    image: mysql:5.7
    secrets:
      - db_name
      - db_user
      - db_password
    environment:
      - "MYSQL_DATABASE_FILE=/run/secrets/db_name"
      - "MYSQL_USER_FILE=/run/secrets/db_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/db_password"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - mysql_volume:/var/lib/mysql
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    restart: always
    networks:
      - network
secrets:
  db_name:
    file: ./secrets_db_name.txt
  db_user:
    file: ./secrets_db_user.txt
  db_password:
    file: ./secrets_db_password.txt
volumes:
  app_volume:
  mysql_volume:
  socket_volume:
networks:
  network:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
